#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT

# export environment variables
export JAVA_HOME="/etc/alternatives/java_sdk_1.8.0"
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR

echo "############################################"
echo "start application with java:"
java -version
echo "############################################"

cd $OPENSHIFT_REPO_DIR
nohup java -jar taboo2-*.jar --spring.profiles.active=openshift,repo-h2 &
